package org.ranc.memberlistapp.domain.model;

public class PhoneBookModel {
	
	
    @Override
	public String toString() {
		return "PhoneBookModel [id=" + id + ", name=" + name + ", phoneNo=" + phoneNo + "]";
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_book.id
     *
     * @mbg.generated Sun Dec 13 00:48:16 JST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_book.name
     *
     * @mbg.generated Sun Dec 13 00:48:16 JST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_book.phone_no
     *
     * @mbg.generated Sun Dec 13 00:48:16 JST 2020
     */
    private String phoneNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_book.id
     *
     * @return the value of phone_book.id
     *
     * @mbg.generated Sun Dec 13 00:48:16 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_book.id
     *
     * @param id the value for phone_book.id
     *
     * @mbg.generated Sun Dec 13 00:48:16 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_book.name
     *
     * @return the value of phone_book.name
     *
     * @mbg.generated Sun Dec 13 00:48:16 JST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_book.name
     *
     * @param name the value for phone_book.name
     *
     * @mbg.generated Sun Dec 13 00:48:16 JST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_book.phone_no
     *
     * @return the value of phone_book.phone_no
     *
     * @mbg.generated Sun Dec 13 00:48:16 JST 2020
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_book.phone_no
     *
     * @param phoneNo the value for phone_book.phone_no
     *
     * @mbg.generated Sun Dec 13 00:48:16 JST 2020
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }
}