package org.ranc.memberlistapp.domain.repository;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Mapper;
import org.ranc.memberlistapp.domain.model.PhoneBookModel;
import org.ranc.memberlistapp.domain.model.PhoneBookModelExample;


@Mapper
public interface PhoneBookRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book
     *
     * @mbg.generated Sun Dec 13 00:48:16 JST 2020
     */
    long countByExample(PhoneBookModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book
     *
     * @mbg.generated Sun Dec 13 00:48:16 JST 2020
     */
    int deleteByExample(PhoneBookModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book
     *
     * @mbg.generated Sun Dec 13 00:48:16 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book
     *
     * @mbg.generated Sun Dec 13 00:48:16 JST 2020
     */
    int insert(PhoneBookModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book
     *
     * @mbg.generated Sun Dec 13 00:48:16 JST 2020
     */
    int insertSelective(PhoneBookModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book
     *
     * @mbg.generated Sun Dec 13 00:48:16 JST 2020
     */
    List<PhoneBookModel> selectByExample(PhoneBookModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book
     *
     * @mbg.generated Sun Dec 13 00:48:16 JST 2020
     */
    PhoneBookModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book
     *
     * @mbg.generated Sun Dec 13 00:48:16 JST 2020
     */
    int updateByExampleSelective(@Param("record") PhoneBookModel record, @Param("example") PhoneBookModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book
     *
     * @mbg.generated Sun Dec 13 00:48:16 JST 2020
     */
    int updateByExample(@Param("record") PhoneBookModel record, @Param("example") PhoneBookModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book
     *
     * @mbg.generated Sun Dec 13 00:48:16 JST 2020
     */
    int updateByPrimaryKeySelective(PhoneBookModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phone_book
     *
     * @mbg.generated Sun Dec 13 00:48:16 JST 2020
     */
    int updateByPrimaryKey(PhoneBookModel record);
}